### ISSUE TITLE
日程の候補など

### ISSUE THREAD

**Issue by MysticDoll** [MysticDoll/newyearparty#6]
書いていってくれ

**Comment by amane-katagiri** [comment]
新年会の時間の想定がわからないが、19:00以降なら金曜がいちばんいいです。次点で任意の土日。

**Comment by oddmutou** [comment]
15以降ならいまのところ予定が無いので大丈夫です。
開始はできれば早い時間のほうが店が空いてそうで嬉しいですが，遅い方に合わせます。自分は17時くらいから動けます。

15日以降の金曜日なら19日がよいのではないでしょうか。

**Comment by oddmutou** [comment]
@MysticDoll 
調整さんあたりで雑にやるのよいのでは

**Comment by MysticDoll** [comment]
拝承！！！！！

**Comment by oddmutou** [comment]
https://chouseisan.com/s?h=dfb1d2ae84ea43c88af4682cdd9f976a
つくりました。参加者各位よろしくです。

**Comment by oddmutou** [comment]
19にしましょう
![screenshot from 2018-01-06 09-26-32](https://user-images.githubusercontent.com/11976067/34634035-b9ff493a-f2c3-11e7-8c0c-5b813d3d965e.png)

**Comment by MysticDoll** [comment]
マージしましたー

**Comment by MysticDoll** [comment]
とりあえずCloseします。
問題ありそうならまたOpenしましょう
